image: python:3.7

pipelines:
  tags:
    airflow-deploy/*:
      - step:
          name: Copy repository to S3 Bucket of Production Airflow
          services:
            - docker  # testing comment
          caches:
            - pip
          script:
            - pip install awscli
            - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            - aws s3 cp $BITBUCKET_CLONE_DIR s3://getir-airflow-elasticfs-prod/repos/${BITBUCKET_REPO_SLUG}/ --recursive --exclude '.git/*'